# Generated by Django 4.1.4 on 2022-12-14 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('base_price', models.FloatField(verbose_name='base price')),
                ('extra_person_price', models.FloatField(verbose_name='extra person price')),
                ('standard_capacity', models.IntegerField(verbose_name='standard capacity')),
                ('maximum_capacity', models.IntegerField(verbose_name='maximum capacity')),
                ('area_size', models.IntegerField(verbose_name='area size')),
                ('build_size', models.IntegerField(verbose_name='build size')),
                ('is_charter', models.BooleanField(default=True, verbose_name='is charter')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'accommodation',
                'verbose_name_plural': 'accommodations',
                'db_table': 'accommodation',
            },
        ),
        migrations.CreateModel(
            name='AccommodationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date join')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='last modify')),
            ],
            options={
                'verbose_name': 'accommodation type',
                'verbose_name_plural': 'accommodations type',
                'db_table': 'accommodation_type',
            },
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date join')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='last modify')),
            ],
            options={
                'verbose_name': 'location type',
                'verbose_name_plural': 'locations type',
                'db_table': 'location_type',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date join')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='last modify')),
            ],
            options={
                'verbose_name': 'room type',
                'verbose_name_plural': 'rooms type',
                'db_table': 'room_type',
            },
        ),
        migrations.CreateModel(
            name='RoomAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='title')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('description', models.CharField(blank=True, max_length=64, null=True, verbose_name='description')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_attribute', to='places.accommodation', verbose_name='room')),
            ],
            options={
                'verbose_name': 'room attribute',
                'verbose_name_plural': 'rooms attribute',
                'db_table': 'room_attribute',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='places.accommodation', verbose_name='accommodation')),
                ('room_type', models.ManyToManyField(related_name='room', to='places.roomtype', verbose_name='room type')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='AccommodationAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='title')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('description', models.CharField(blank=True, max_length=64, null=True, verbose_name='description')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_attribute', to='places.accommodation', verbose_name='accommodation')),
            ],
            options={
                'verbose_name': 'accommodation attribute',
                'verbose_name_plural': 'accommodations attribute',
                'db_table': 'accommodation_attribute',
            },
        ),
        migrations.AddField(
            model_name='accommodation',
            name='accommodation_type',
            field=models.ManyToManyField(related_name='accommodation', to='places.accommodationtype', verbose_name='accommodation type'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='location_type',
            field=models.ManyToManyField(related_name='accommodation', to='places.locationtype', verbose_name='location type'),
        ),
    ]
