# Generated by Django 4.1.4 on 2022-12-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Place',
            new_name='place',
        ),
        migrations.AddField(
            model_name='option',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='is free'),
        ),
    ]
