# Generated by Django 4.1.4 on 2023-01-19 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='placerate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placedateprice',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_price', to='places.accommodation', verbose_name='accommodation'),
        ),
        migrations.AddField(
            model_name='placedateprice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_%(class)ss', to='places.placecomment'),
        ),
        migrations.AddField(
            model_name='placecomment',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_comment', to='places.place', verbose_name='place'),
        ),
        migrations.AddField(
            model_name='placecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placecomment',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validated_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='place',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='place_location', to='places.location', verbose_name='location'),
        ),
        migrations.AddField(
            model_name='place',
            name='location_type',
            field=models.ManyToManyField(related_name='accommodation', to='places.locationtype', verbose_name='location type'),
        ),
        migrations.AddField(
            model_name='place',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Accommodation', to=settings.AUTH_USER_MODEL, verbose_name='Accommodation'),
        ),
        migrations.AddField(
            model_name='accommodationroom',
            name='accommodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='places.accommodation', verbose_name='accommodation'),
        ),
        migrations.AddField(
            model_name='accommodationroom',
            name='attribute',
            field=models.ManyToManyField(related_name='accommodation_room', to='places.accommodationroomattribute', verbose_name='attribute'),
        ),
        migrations.AddField(
            model_name='accommodationroom',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_room', to='places.roomtype', verbose_name='room_type'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='accommodation_type',
            field=models.ManyToManyField(related_name='accommodation', to='places.accommodationtype', verbose_name='accommodation type'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='attribute',
            field=models.ManyToManyField(related_name='accommodation', to='places.accommodationattribute', verbose_name='attribute'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accommodation', to='places.place', verbose_name='place'),
        ),
        migrations.AlterUniqueTogether(
            name='placerate',
            unique_together={('place', 'user')},
        ),
    ]
