# Generated by Django 4.1.4 on 2023-01-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placedateprice',
            old_name='person_numbers',
            new_name='person_number',
        ),
    ]
