# Generated by Django 4.1.4 on 2023-01-11 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_person_numbers_placedateprice_person_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationroom',
            name='accommodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='places.accommodation', verbose_name='accommodation'),
        ),
    ]
