# Generated by Django 4.1.4 on 2022-12-22 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_accommodation_place_location_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationdateprice',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_price', to='places.accommodation', verbose_name='accommodation'),
        ),
        migrations.AlterField(
            model_name='roomdateprice',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_price', to='places.room', verbose_name='accommodation'),
        ),
    ]
