# Generated by Django 4.1.4 on 2023-01-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_accommodationroom_accommodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedateprice',
            name='person_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='person number'),
        ),
    ]
