# Generated by Django 4.1.4 on 2022-12-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_accommodationdateprice_accommodation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='base_price',
            field=models.FloatField(blank=True, null=True, verbose_name='bace price'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_accommodation',
            field=models.BooleanField(default=True, verbose_name='is accommodation'),
        ),
    ]
