# Generated by Django 4.1.4 on 2022-12-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_room_base_price_room_is_accommodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='currency',
            field=models.PositiveIntegerField(choices=[(1, 'IRR'), (2, 'USD')], default=1, verbose_name='currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accommodationdateprice',
            name='currency',
            field=models.PositiveIntegerField(choices=[(1, 'IRR'), (2, 'USD')], default=1, verbose_name='currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='currency',
            field=models.PositiveIntegerField(choices=[(1, 'IRR'), (2, 'USD')], default=1, verbose_name='currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomdateprice',
            name='currency',
            field=models.PositiveIntegerField(choices=[(1, 'IRR'), (2, 'USD')], default=1, verbose_name='currency'),
            preserve_default=False,
        ),
    ]
