# Generated by Django 4.1.4 on 2023-01-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_accommodation_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='currency',
            field=models.PositiveIntegerField(choices=[(1, 'IRR'), (2, 'USD'), (3, 'EUR'), (4, 'CAD')], verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='accommodationdateprice',
            name='currency',
            field=models.PositiveIntegerField(choices=[(1, 'IRR'), (2, 'USD'), (3, 'EUR'), (4, 'CAD')], verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='roomdateprice',
            name='currency',
            field=models.PositiveIntegerField(choices=[(1, 'IRR'), (2, 'USD'), (3, 'EUR'), (4, 'CAD')], verbose_name='currency'),
        ),
    ]
