# Generated by Django 4.1.4 on 2023-01-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'cancel'), (1, 'unpaid'), (2, 'paid'), (3, 'payment failed')], default=0, verbose_name='status')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update date')),
            ],
            options={
                'verbose_name': 'accommodation order',
                'verbose_name_plural': 'accommodation orders',
                'db_table': 'accommodation_orders',
            },
        ),
        migrations.CreateModel(
            name='HotelRoomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'cancel'), (1, 'unpaid'), (2, 'paid'), (3, 'payment failed')], default=0, verbose_name='status')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update date')),
            ],
            options={
                'verbose_name': 'hotel room order',
                'verbose_name_plural': 'hotel room orders',
                'db_table': 'hotel_room_order',
            },
        ),
    ]
