# Generated by Django 4.1.4 on 2023-01-04 14:36

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('places', '0003_alter_place_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(verbose_name='status')),
                ('date_prices', models.ManyToManyField(related_name='hotel_room_orders', to='places.hotelroomdateprice', verbose_name='date prices')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_room_order', to='places.place', verbose_name='hotel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'hotel room order',
                'verbose_name_plural': 'hotel room orders',
                'db_table': 'hotel_room_order',
            },
        ),
        migrations.CreateModel(
            name='AccommodationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(verbose_name='status')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='places.accommodation', verbose_name='accommodation')),
                ('date_prices', models.ManyToManyField(related_name='accommodation_orders', to='places.accommodationdateprice', verbose_name='date price')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'accommodation order',
                'verbose_name_plural': 'accommodation orders',
                'db_table': 'accommodation_orders',
            },
        ),
    ]
