# Generated by Django 4.1.4 on 2023-01-04 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseOrder',
            new_name='OrderBace',
        ),
        migrations.CreateModel(
            name='HotelRoomOrder',
            fields=[
                ('orderbace_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='carts.orderbace')),
                ('date_prices', models.ManyToManyField(related_name='hotel_room_orders', to='places.hotelroomdateprice', verbose_name='date prices')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='places.place', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'hotel room order',
                'verbose_name_plural': 'hotel room orders',
                'db_table': 'hotel_room_order',
            },
            bases=('carts.orderbace',),
        ),
        migrations.CreateModel(
            name='AccommodationOrder',
            fields=[
                ('orderbace_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='carts.orderbace')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='places.accommodation', verbose_name='accommodation')),
                ('date_price', models.ManyToManyField(related_name='accommodation_orders', to='places.accommodationdateprice', verbose_name='accommodation')),
            ],
            options={
                'verbose_name': 'accommodation order',
                'verbose_name_plural': 'accommodation orders',
                'db_table': 'accommodation_order',
            },
            bases=('carts.orderbace',),
        ),
    ]
