# Generated by Django 4.1.4 on 2023-01-19 13:42

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('places', '0001_initial'),
        ('carts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flying', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='placeorder',
            name='date_prices',
            field=models.ManyToManyField(related_name='place_orders', to='places.placedateprice', verbose_name='date price'),
        ),
        migrations.AddField(
            model_name='placeorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='placeitem',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='place_items', to='flying.flyticket'),
        ),
        migrations.AddField(
            model_name='placeitem',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='place_item', to='carts.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='flyitem',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='fly_items', to='places.placedateprice'),
        ),
        migrations.AddField(
            model_name='flyitem',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fly_item', to='carts.order'),
        ),
    ]
