# Generated by Django 4.1.4 on 2023-01-08 09:47

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='hotelroomorder',
            name='date_prices',
            field=models.ManyToManyField(related_name='hotel_room_orders', to='places.hotelroomdateprice', verbose_name='date prices'),
        ),
        migrations.AddField(
            model_name='hotelroomorder',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_room_order', to='places.place', verbose_name='hotel'),
        ),
        migrations.AddField(
            model_name='hotelroomorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='accommodationorder',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='places.accommodation', verbose_name='accommodation'),
        ),
        migrations.AddField(
            model_name='accommodationorder',
            name='date_prices',
            field=models.ManyToManyField(related_name='accommodation_orders', to='places.accommodationdateprice', verbose_name='date price'),
        ),
        migrations.AddField(
            model_name='accommodationorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
