# Generated by Django 4.1.4 on 2023-01-05 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_accommodationorder_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationorder',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='create_date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accommodationorder',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='update date'),
        ),
        migrations.AddField(
            model_name='hotelroomorder',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='create_date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelroomorder',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='update date'),
        ),
    ]
