# Generated by Django 4.1.4 on 2023-01-10 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='name')),
                ('logo', models.ImageField(upload_to='airline-logo/', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'airline',
                'verbose_name_plural': 'airlines',
                'db_table': 'airline',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date join')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='last modify')),
                ('title', models.CharField(max_length=64, verbose_name='name')),
                ('abbreviated_name', models.CharField(default=models.CharField(max_length=64, verbose_name='name'), max_length=16, verbose_name='abbreviated name')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='location', to='places.location', verbose_name='location')),
            ],
            options={
                'verbose_name': 'airport',
                'verbose_name_plural': 'airports',
                'db_table': 'airport',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date join')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='last modify')),
                ('national_symbol', models.CharField(max_length=8, unique=True, verbose_name='national symbol')),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_from', models.PositiveIntegerField(choices=[(1, 'IRR'), (2, 'USD')], default=1, verbose_name='currency from')),
                ('currency_to', models.PositiveIntegerField(default=1, verbose_name='currency to')),
                ('rate', models.FloatField(verbose_name='rate')),
            ],
        ),
        migrations.CreateModel(
            name='FlightRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date join')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='last modify')),
                ('description', models.TextField(blank=True, null=True, verbose_name='flight rule')),
                ('is_penalty', models.BooleanField(default=True, verbose_name='is penalty')),
            ],
            options={
                'verbose_name': 'flight rule',
                'verbose_name_plural': 'flights rules',
                'db_table': 'flight_rule',
            },
        ),
        migrations.CreateModel(
            name='PassengerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='first name')),
                ('last_name', models.CharField(max_length=64, verbose_name='last name')),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'male'), (2, 'female')], verbose_name='gender')),
                ('nationality', models.CharField(max_length=64, verbose_name='nationality')),
                ('national_id', models.CharField(max_length=64, verbose_name='national id')),
                ('passport_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='passport number')),
                ('birthday', models.DateField(verbose_name='birthday')),
                ('passport_expire_date', models.DateField(verbose_name='passport expire date')),
            ],
            options={
                'verbose_name': 'passenger information',
                'verbose_name_plural': 'passengers information',
                'db_table': 'passenger_information',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date join')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='last modify')),
                ('flight_number', models.IntegerField(verbose_name='flight number')),
                ('fly_dateTime', models.DateTimeField(verbose_name='fly datetime')),
                ('landing_datetime', models.DateTimeField(verbose_name='landing datetime')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_airline', to='flying.airline', verbose_name='airline')),
                ('carried_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_carried_by', to='flying.airline', verbose_name='carried by')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_destination', to='flying.airport', verbose_name='destination')),
                ('flight_rules', models.ManyToManyField(related_name='flight', to='flying.flightrule', verbose_name='flight rules')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_source', to='flying.airport', verbose_name='source')),
            ],
            options={
                'verbose_name': 'flight',
                'verbose_name_plural': 'flights',
                'db_table': 'flight',
            },
        ),
        migrations.CreateModel(
            name='AirTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='is valid')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date join')),
                ('last_modify', models.DateTimeField(auto_now=True, verbose_name='last modify')),
                ('is_international_flight', models.BooleanField(verbose_name='is international flight')),
                ('flight_time', models.TimeField(blank=True, null=True, verbose_name='flight time')),
                ('stop_time', models.TimeField(blank=True, null=True, verbose_name='stop time')),
                ('adults_price', models.FloatField(verbose_name='adult_price')),
                ('children_price', models.FloatField(verbose_name='adult_price')),
                ('infant_price', models.FloatField(verbose_name='infant price')),
                ('currency', models.CharField(default='IRR', max_length=16, verbose_name='currency')),
                ('final_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_destination', to='flying.airport', verbose_name='final destination')),
                ('flights', models.ManyToManyField(related_name='air_travel', to='flying.flight', verbose_name='flights')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='flying.airport', verbose_name='origin')),
                ('stop_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air_travel_stop', to='places.location', verbose_name='stop in')),
            ],
            options={
                'verbose_name': 'air travel',
                'verbose_name_plural': 'air travels',
                'db_table': 'air_travel',
            },
        ),
    ]
