# Generated by Django 4.1.4 on 2023-01-08 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flying', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtravel',
            name='stop_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air_travel_stop', to='places.location', verbose_name='stop in'),
        ),
        migrations.AddField(
            model_name='airport',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='location', to='places.location', verbose_name='location'),
        ),
    ]
