# Generated by Django 4.1.4 on 2023-01-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flying', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchange',
            name='currency_to',
            field=models.PositiveIntegerField(choices=[(1, 'IRR'), (2, 'USD')], default=1, verbose_name='currency to'),
        ),
    ]
