# Generated by Django 4.1.4 on 2023-01-19 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flying', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fly_ticket', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_airline', to='flying.airline', verbose_name='airline'),
        ),
        migrations.AddField(
            model_name='flight',
            name='carried_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_carried_by', to='flying.airline', verbose_name='carried by'),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_destination', to='flying.airport', verbose_name='destination'),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_rules',
            field=models.ManyToManyField(related_name='flight', to='flying.flightrule', verbose_name='flight rules'),
        ),
        migrations.AddField(
            model_name='flight',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_source', to='flying.airport', verbose_name='source'),
        ),
        migrations.AddField(
            model_name='airtravel',
            name='airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airline_airline', to='flying.airline', verbose_name='airline'),
        ),
        migrations.AddField(
            model_name='airtravel',
            name='final_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_destination', to='flying.airport', verbose_name='final destination'),
        ),
        migrations.AddField(
            model_name='airtravel',
            name='flights',
            field=models.ManyToManyField(related_name='air_travel', to='flying.flight', verbose_name='flights'),
        ),
        migrations.AddField(
            model_name='airtravel',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='flying.airport', verbose_name='origin'),
        ),
        migrations.AddField(
            model_name='airtravel',
            name='stop_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air_travel_stop', to='places.location', verbose_name='stop in'),
        ),
        migrations.AddField(
            model_name='airport',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='location', to='places.location', verbose_name='location'),
        ),
        migrations.AlterUniqueTogether(
            name='flyticket',
            unique_together={('seat_number', 'air_travel')},
        ),
    ]
