# Generated by Django 4.1.4 on 2022-12-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flying', '0002_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_from', models.PositiveIntegerField(choices=[(1, "b'IRR'"), (2, "b'USD'")], default=1, verbose_name='currency from')),
                ('currency_to', models.PositiveIntegerField(default=1, verbose_name='currency to')),
                ('rate', models.FloatField(verbose_name='rate')),
            ],
        ),
    ]
