# Generated by Django 4.1.4 on 2022-12-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flying', '0003_currencyexchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchange',
            name='currency_from',
            field=models.PositiveIntegerField(choices=[(1, 'IRR'), (2, 'USD')], default=1, verbose_name='currency from'),
        ),
    ]
