# Generated by Django 4.1.4 on 2023-01-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flying', '0004_airtravel_airline'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtravel',
            name='fly_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fly datetime'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='abbreviated_name',
            field=models.CharField(max_length=16, verbose_name='abbreviated name'),
        ),
    ]
