# Generated by Django 4.1.4 on 2023-01-19 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flying', '0006_alter_airtravel_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlyTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.PositiveIntegerField(choices=[(1, 'IRR'), (2, 'USD'), (3, 'EUR'), (4, 'CAD')], verbose_name='currency')),
                ('is_reserve', models.BooleanField(default=False, verbose_name='is reserve')),
                ('date', models.DateField(verbose_name='date')),
                ('price', models.FloatField(verbose_name='price')),
                ('seat_number', models.PositiveIntegerField(verbose_name='seat_number')),
                ('air_travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fly_ticket', to='flying.airtravel', verbose_name='air travel')),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fly_ticket', to='flying.passengerinformation', verbose_name='passenger')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fly_ticket', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'fly ticket',
                'verbose_name_plural': 'fly tickets',
                'db_table': 'fly ticket',
                'unique_together': {('seat_number', 'air_travel')},
            },
        ),
    ]
